// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef chatGui_h
#define chatGui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Check_Browser.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>

class UserInterface {
public:
  Fl_Double_Window* make_window();
  Fl_Check_Browser *bodyBrowser;
  Fl_Text_Display *chatlogTxt;
  Fl_Input *serverTxt;
  Fl_Input *portTxt;
  Fl_Button *connectBtn;
  Fl_Input *msgTxt;
  Fl_Button *sendBtn;
};
#endif
